version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_front
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev

  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_story
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "6006:6006"
    command: npm run storybook
