version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: recipe_front
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
